title: My Wild Ride
author: J Blake
email: blakej@alumni.uoguelph.ca
description: > # this means to ignore newlines until "baseurl:"
  My journey to becoming a Software Engineer. Started from the bottom now we where?

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jermzblake # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
